baseURL = "https://www.phantisocracy.xyz"
languageCode = "en-us"
title = "Phantisocracy"
paginate = 5

copyright = "© 2020 by Matthew Edward Adams"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#googleAnalytics = "UA-123-45"
disqusShortname = "https-www-phtantisocracy-xyz"

summaryLength = 20

[params]
	subtitle = "The public workspace of Matthew Edward Adams"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Sundries"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/linguistgate"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/matthew.e.adams"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/linguistgate"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
